                    	<h3 class="prev-indent-bot2">Testimonials</h3>
                        <div class="wrapper">
                        	<article class="grid_6 alpha">
                            	<div class="indent-right img-indent-bot">
                                    <blockquote>
                                        <div class="quote">
                                            <div class="padding">
                                                &quot;Lorem ipsum dolor sit amet, consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.&quot;
                                            </div>
                                        </div>
                                    </blockquote>
                                    <div class="aligncenter text-2">
                                        <strong>John Williams</strong>
                                        <p class="p0 color-1">Director</p>
                                    </div>
                                </div>
                            </article>
                            <article class="grid_6 omega">
                            	<div class="indent-left">
                                    <blockquote>
                                        <div class="quote">
                                            <div class="padding">
                                                &quot;Ut enim minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.&quot;
                                            </div>
                                        </div>
                                    </blockquote>
                                    <div class="aligncenter text-2">
                                        <strong>Kate Holmes</strong>
                                        <p class="p0 color-1">Manager</p>
                                    </div>
                                </div>
                            </article>
                        </div>