	<footer>
        <div class="main">
        	<div class="container_12">
            	<div class="wrapper">
                	<article class="grid_3">
                    	<ul class="list-services">
                        	<li class="item-1"><a class="tooltips" title="facebook" href="#"></a></li>
                            <li class="item-2"><a class="tooltips" title="twiiter" href="#"></a></li>
                            <li class="item-3"><a class="tooltips" title="delicious" href="#"></a></li>
                            <li class="item-4"><a class="tooltips" title="youtube" href="#"></a></li>
                        </ul>
                    </article>
                    <article class="grid_3">
                    	<div class="indent-left2">
                            <h5>Navigation</h5>
                            <ul class="list-1">
                                <li><a href="home.do">Home</a></li>
                                <li><a href="company.do">Company</a></li>
                                <li><a href="services.do">Services</a></li>
                                <li><a href="clients.do">Clients</a></li>
                                <li><a href="contacts.do">Contacts</a></li>
                            </ul>
                        </div>
                    </article>
                    <article class="grid_3">
                    	<h5>Contact</h5>
                        <dl class="contact">
                            <dt>2256 S Norfolk Street<br>Seattle, WA<br>98118-5648</dt>
                            <dd><span>Phone:</span>  217-764-7449</dd>
                            <dd><span>Fax:</span>  217-763-7912</dd>
                         </dl>
                    </article>
                    <article class="grid_3">
                    	<h5>Legal</h5>
                        <p class="prev-indent-bot3 color-1">Wise Solutions &copy; 2011</p>
                        <p class="prev-indent-bot3"><a class="link" target="_blank" href="http://www.templatemonster.com/">Website Template</a></p>
                        <p class="color-1 p0">by TemplateMonster.com</p>
						<p class="color-1 p0">More <a href="http://www.websitetemplatesonline.com" title="WTO - website templates and Flash templates">Free Web Templates</a> at WTO. All <a href="http://www.magentothemesworld.com" title="Best Magento Templates">premium Magento themes</a> at magentothemesworld.com!</p>
                    </article>
                </div>
            </div>
        </div>
    </footer>