
                    	<h3>News</h3>
                        <div class="indent-bot">
                        	<time class="tdate-1" datetime="2011-12-24"><strong>24</strong>dec</time>
                            <div class="extra-wrap">
                            	<h6><a class="link" href="index.jsp#">Ut enim ad minim veniam quis nostrud </a></h6>
                                Exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="indent-bot">
                        	<time class="tdate-1" datetime="2011-12-21"><strong>21</strong>dec</time>
                            <div class="extra-wrap">
                            	<h6><a class="link" href="index.jsp#">Duis auterure dolor reprehenderit</a></h6>
                                Voluptate velit esse cillum dolore eu fugiat nulla<br> pariatur xcepteur sint occaecat.
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="p3">
                        	<time class="tdate-1" datetime="2011-12-09"><strong>09</strong>dec</time>
                            <div class="extra-wrap">
                            	<h6><a class="link" href="index.jsp#">Cupidatat non proident sunt in culpa </a></h6>
                                Ceserunt mollit anim est laborum tempor incididunt ut labore et dolore magna aliqua.
                            </div>
                            <div class="clear"></div>
                        </div>
                        